# Title of your site
title: "svmadhurapantula-portfolio.github.io"  # Replace with your actual site title

# Logo of your site (URL or path to the image)
logo:  # Add the path or URL to your logo

# Description of your site
description: Portfolio  # Replace with your actual description

# Show download links for projects
show_downloads: true  # Set to false if you don't want to show download links

# Theme for the site
theme: jekyll-theme-minimal  # The name of the theme you are using
